export const data = [

  {
    id: 1,
    userName: "Virat Kohli",
    title: "➥ㅤ" + "Virat Kohli is an Indian cricketer who plays Test and ODI cricket for the national team. He is a right-handed batsman and an occasional right arm medium pace bowler. He is called the king and the chase master for his playing style, skill and records.\n\n" + "➥ㅤ" + "Kohli was a member of the team that won the 2008 U19 World Cup, 2011 ODI World Cup, 2013 Champions Trophy and 2024 T20 World Cup. He captained them to win the Test mace three consecutive times in 2017, 2018, and 2019. He represents Royal Challengers Bengaluru in the Indian Premier League and Delhi in domestic cricket. In 2013, Kohli was ranked number one in the ODI batsmen rankings. In 2015, he achieved the same for T20I rankings. In 2018, he was ranked the top Test batsman, making him the only Indian cricketer to hold the number one spot in all three formats. He is the first player to score 20,000 runs in a decade. In 2020, ICC named him the male cricketer of the decade.\n\n" + "➥ㅤ" + "Kohli has garnered 10 ICC Awards making him the most awarded player ininternational cricket history. He was honored with the Arjuna Award in 2013, the Padma Shri in 2017, and India's highest sporting , the Khel Ratna Award,in 2018. After winning the 2024 T20 World Cup and the Player of the Match in the final, Kohli announced his retirement from T20Is.",
    mImg: "https://media.gettyimages.com/id/1435854570/photo/melbourne-australia-virat-kohli-of-india-celebrates-winning-the-icc-mens-t20-world-cup-match.jpg?s=612x612&w=0&k=20&c=FPVF8aGhGAYbT-8CDZCVbO2kEpDdyveTycJTEUSsLHs="
  },
  {
    id: 2,
    userName: "Rohit Sharma",
    title: "➥ㅤ" + "Rohit Sharma is an Indian cricketer and the captain of national cricket team in Test and ODI formats. He is widely regarded as one of the greatest opening batters in limited overs cricket of all time. He is also known as one of the greatest six hitters in cricket history. He is a right-handed batsman who plays for Mumbai Indians in Indian Premier League and for Mumbai in domestic cricket. Rohit previously captained India in all three formats. After leading the victory at the 2024 Men's T20 World Cup, he announced his retirement from T20Is.\n\n" + "➥ㅤ" + "He holds several batting records which famously include most runs in T20 Internationals, most sixes in international cricket, most double centuries in ODI cricket, most centuries at Cricket World Cups (7) and joint most hundreds in Twenty20 Internationals (5). He is the first player to score 5 T20I centuries,and holds record of hitting fastest T20I century in 35 balls. He also holds the world record for the highest individual score (264) in a One Day International (ODI) match and is the only player to have scored three double-centuries in ODIs and also holds the record for scoring most hundreds (five) in a single Cricket World Cup, for which he won the ICC Men's ODI Cricketer of the Year award in 2019. He is the only player to win 50 matches as captain in T20Is.[8] He is the first and only captain to lead a team in all[b] ICC tournament finals.",
    mImg: "https://media.gettyimages.com/id/1729735326/photo/delhi-india-rohit-sharma-of-india-celebrates-their-century-during-the-icc-mens-cricket-world.jpg?s=612x612&w=0&k=20&c=v7jra4OUcOHTyAGhOWYpRyAI8pSaj5_lE0IgHai_ABg=",

  },
  {
    id: 3,
    userName: "Hardik Pandya",
    title: "➥ㅤ" + "Hardik Himanshu Pandya (born 11 October 1993) is an Indian international cricketer who plays for the Indian cricket team. He is an all-rounder who is a right-handed middle order batsman and fast-medium bowler. He is considered one of the best all-rounders in the world in white-ball cricket, known for his clutch performances in important matches. Pandya has represented India in all 3 formats. He captains Mumbai Indians in the Indian Premier League (IPL), and occasionally plays for his regional team Baroda in domestic cricket. He has captained the Indian team in white-ball cricket and was the vice captain of the team that won the 2024 T20 World Cup.\n\n" + "➥ㅤ" + "Hardik Pandya's Magical 2022 IPL Campaign  Hardik Pandya's performance in the 2022 Indian Premier League (IPL) was a remarkable display of leadership and all-round cricketing prowess. As the captain of the newly formed Gujarat Titans, Pandya led his team to their maiden IPL title in a season that saw him excel both with the bat and the ball, and as a strategic leader.\n\n" + "➥ㅤ" + "One of Pandya's largest contributions came during India's 2024 T20 World Cup campaign. He was clinical with both the ball and the bat.",
    mImg: "https://media.gettyimages.com/id/2159834353/photo/final-icc-mens-t20-cricket-world-cup-west-indies-usa-2024.jpg?s=612x612&w=gi&k=20&c=aykA8rTy_gqEuwHMptm6uSr9anHfIKwpe8RKo454Jsc="
  },
  {
    id: 4,
    userName: "KL Rahul",
    title: "➥ㅤ" + "Kannaur Lokesh Rahul born 18 April 1992) is an Indian international cricketer who plays for the Indian national team and will play for Delhi Capitals in the Indian Premier League 2025. A right-handed wicket-keeper batter, he plays for Karnataka in domestic cricket.\n\n" + "➥ㅤ" + "Rahul made his international debut in 2014 against Australia in the Boxing Day Test in Melbourne. Two years after his Test debut, Rahul made his One-Day International debut in 2016 against Zimbabwe, where he scored his first century by hitting a six on the last ball to reach 100* (115) from 94 (114), which was also the only six of the entire match. Rahul is the first and only Indian cricketer to score an ODI century on his debut. On the same tour, he made his T20I debut. He is the fastest batsman in the world to score a century across all three formats of international cricket, taking only twenty innings.\n\n" + "➥ㅤ" + "Rahul made his Indian Premier League (IPL) debut for Royal Challengers Bangalore (RCB) during the 2013 season. Ahead of the 2014 IPL, he was bought by the Sunrisers Hyderabad for INR 1 crore. Rahul was selected in the ODI squad for the home series against England and Champions Trophy 2025.",
    mImg: "https://media.gettyimages.com/id/1789243378/photo/bangalore-india-kl-rahul-of-india-celebrates-his-century-during-the-icc-mens-cricket-world.jpg?s=612x612&w=gi&k=20&c=5gmTwybijZ53GOpU0JuBcx6ZSsTQ4yAxlu_jjHOZqiE=",

  },
  {
    id: 5,
    userName: "Ravindra Jadeja",
    title: "➥ㅤ" + "Ravindrasinh Anirudhsinh Jadeja (born 6 December 1988) is an Indian international cricketer who represents the Indian national cricket team in ODI and Test formats. He is an all-rounder, who bats left-handed and bowls left-arm orthodox spin. He is regarded as one of the best all-rounders of his generation, becoming the fifth Indian and fifth-fastest player to score 2,000 runs and take 200 wickets in Test cricket in 2021. Jadeja was the leading wicket-taker in the 2013 ICC Champions Trophy and received the man of the match award as a member of the final-winning team. Later in his career, he was also a part of the team which won the 2024 T20 World Cup, after which he announced his retirement from the T20Is. He represents Saurashtra in first-class cricket and has captained the Chennai Super Kings in the Indian Premier League. As of August 2023, Ravindra Jadeja is the 7th highest ODI wicket taker for India with 220 wickets.\n\n" + "➥ㅤ" + "2012 IPL player auction, Jadeja was bought by Chennai Super Kings for $2 million after a tie-breaker with Deccan Chargers who bid the same amount. Jadeja was the most expensive player of the year's auction. He won the Man of the Match award in the second match of the season. In the final of the 2023 Indian Premier League final, Chennai Super Kings required 10 from the final two balls. Jadeja hit a 6 and 4 to give CSK the title." ,
    mImg: "https://media.licdn.com/dms/image/v2/C5622AQFEwGJ38JuHTA/feedshare-shrink_800/feedshare-shrink_800/0/1661258841046?e=2147483647&v=beta&t=_n8WUaPbHG8OfPY8iF0anfXeBCfr0zjfgdLcHO3hbd0",

  },
];

